### ISSUE TITLE
could not reproduce the res in the paper 

### ISSUE THREAD

**Issue by knightyxp** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#19]
the published code do not have CANet branch, not coordinated with the paper report, the baseline of SFANet is 59 according to my exp, however, when I add ASPP(means using the M-SFANet model according to the author's code) the SHA MAE is only 61, ridiculous, the res in the paper can not be reproduced (i do not know whether the reviewer of ICPR know this thing)

**Comment by knightyxp** [comment]
![截屏2021-05-20 下午6 58 46](https://user-images.githubusercontent.com/48432506/118967530-688ce400-b99d-11eb-9deb-016362594be2.png)

**Comment by Pongpisit-Thanasutives** [comment]
In the ScalePyramidModule class, defined in M-SFANet.py, there is self.can = ContextualModule(512, 512) as the CANet branch. If the CAN module is deducted, the reported performance was 62.41 (MAE) on SHA and 7.40 (MAE) on SHB. Please ensure to include the module in your forward pass as well.

**Comment by knightyxp** [comment]
i already add the ScalePyramidModule as you can see but the res is 61, not as good as only sfan(59) , not same with the res in your paper 59.69, 
<img width="641" alt="截屏2021-05-21 上午12 42 43" src="https://user-images.githubusercontent.com/48432506/119017324-765a5d80-b9cd-11eb-8197-61cf976b6280.png">

**Comment by knightyxp** [comment]
whether this means just add can in sfan is not suitable

**Comment by knightyxp** [comment]
what is more, in your exp M-SFANet w/o CAN(this means just sfan)   the MAE on SHA is 62.41, however the sfan on sha could achieve 59(my exp) reported 60 , so i do not know how u get this res
<img width="769" alt="截屏2021-05-21 上午12 49 12" src="https://user-images.githubusercontent.com/48432506/119018151-5ecfa480-b9ce-11eb-9188-95e433176478.png">

**Comment by Pongpisit-Thanasutives** [comment]
@knightyxp I see. M-SFANet w/o CAN means deducting self.can in ScalePyramidModule. Can I have your training code? It's hard to notice the difference in implementation.

**Comment by knightyxp** [comment]
same as  train.py in sfanet

**Comment by knightyxp** [comment]
import torch
from torch import nn
from torch import optim
from torch.utils import data
from dataset import Dataset
import sys
sys.path.append('/home/yangxiangpeng/.jupyter/SFANet-crowd-counting')
from model import Model
#from models.M_SFANet import Model
from tensorboardX import SummaryWriter
import os
import argparse
from utils.losses import *
from utils import pytorch_ssim


parser = argparse.ArgumentParser()
parser.add_argument('--bs', default=8, type=int, help='batch size')
parser.add_argument('--epoch', default=500, type=int, help='train epochs')
parser.add_argument('--dataset', default='SHA', type=str, help='dataset')
parser.add_argument('--data_path', default=r'/home/yangxiangpeng/.jupyter/data', type=str, help='path to dataset')
parser.add_argument('--lr', default=1e-4, type=float, help='initial learning rate')
parser.add_argument('--load', default=False, action='store_true', help='load checkpoint')
parser.add_argument('--save_path', default=r'/home/yangxiangpeng/.jupyter/SFANet-crowd-counting/logs/sha', type=str, help='path to save checkpoint')
parser.add_argument('--gpu', default=0, type=int, help='gpu id')
parser.add_argument('--log_path', default='./logs', type=str, help='path to log')

args = parser.parse_args()

print(args.data_path)

train_dataset = Dataset(args.data_path, args.dataset, True)
#print(train_dataset)
print(len(train_dataset))
train_loader = data.DataLoader(train_dataset, batch_size=args.bs, shuffle=True)
print(len(train_loader))
test_dataset = Dataset(args.data_path, args.dataset, False)
print(len(test_dataset))
test_loader = data.DataLoader(test_dataset, batch_size=1, shuffle=False)
print(len(test_loader))
          
         

#device = torch.device('cuda:' + str(args.gpu))
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
model = Model().to(device)
model.cuda()

writer = SummaryWriter(args.log_path)

mseloss = nn.MSELoss(reduction='sum').to(device)
bceloss = nn.BCELoss(reduction='sum').to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

if args.load:
    checkpoint = torch.load(os.path.join(args.save_path, 'checkpoint_latest.pth'))
    model.load_state_dict(checkpoint['model'])
    optimizer.load_state_dict(checkpoint['optimizer'])

    best_mae = torch.load(os.path.join(args.save_path, 'checkpoint_best.pth'))['mae']
    start_epoch = checkpoint['epoch'] + 1
else:
    best_mae = 999999
    start_epoch = 0

for epoch in range(start_epoch, start_epoch + args.epoch):
    loss_avg, loss_att_avg = 0.0, 0.0
    for i, (images, density, att) in enumerate(train_loader):
        images = images.to(device)
        density = density.to(device)
        att = att.to(device)
        outputs, attention = model(images)

        print('output:{:.2f} label:{:.2f}'.format(outputs.sum().item() / args.bs, density.sum().item() / args.bs))

        loss = mseloss(outputs, density) / args.bs
        loss_att = bceloss(attention, att) / args.bs * 0.1
        
        
        ssim_loss = pytorch_ssim.SSIM(window_size=11)

        #loss_sum = loss + loss_att
        loss_sum = loss + loss_att + (1 - ssim_loss(outputs,density))

        optimizer.zero_grad()
        loss_sum.backward()
        optimizer.step()

        loss_avg += loss.item()
        loss_att_avg += loss_att.item()

        print("Epoch:{}, Step:{}, Loss:{:.4f} {:.4f}".format(epoch, i, loss_avg / (i + 1), loss_att_avg / (i + 1)))
    
    writer.add_scalar('loss/train_loss', loss_avg / len(train_loader), epoch)
    writer.add_scalar('loss/train_loss_att', loss_att_avg / len(train_loader), epoch)

    model.eval()
    with torch.no_grad():
        mae, mse = 0.0, 0.0
        for i, (images, gt) in enumerate(test_loader):
            images = images.to(device)
            gt = gt.to(device)
            predict, _ = model(images)
            #print(gt.size())
            #print(predict.sum())
            #print(gt)
            print('predict:{:.2f} label:{:.2f}'.format(predict.sum().item(), gt.sum().item()))
            mae += torch.abs(predict.sum() - gt.sum()).item()
            mse += ((predict.sum() - gt.sum()) ** 2).item()

        mae /= len(test_loader)
        mse /= len(test_loader)
        mse = mse ** 0.5
        print('Epoch:', epoch, 'MAE:', mae, 'MSE:', mse)
        writer.add_scalar('eval/MAE', mae, epoch)
        writer.add_scalar('eval/MSE', mse, epoch)

        state = {'epoch': epoch, 'model': model.state_dict(), 'optimizer': optimizer.state_dict(), 'mae': mae,
                 'mse': mse}
        torch.save(state, os.path.join(args.save_path, 'checkpoint_latest.pth'))

        if mae < best_mae:
            best_mae = mae
            torch.save(state, os.path.join(args.save_path, 'checkpoint_best.pth'))
    model.train()
    

writer.close()

**Comment by knightyxp** [comment]
import torch
from torch import nn
from torch import optim
from torch.utils import data
from dataset import Dataset
import sys
sys.path.append('/home/yangxiangpeng/.jupyter/SFANet-crowd-counting')
from model import Model
#from models.M_SFANet import Model
from tensorboardX import SummaryWriter
import os
import argparse
from utils.losses import *
from utils import pytorch_ssim


parser = argparse.ArgumentParser()
parser.add_argument('--bs', default=8, type=int, help='batch size')
parser.add_argument('--epoch', default=500, type=int, help='train epochs')
parser.add_argument('--dataset', default='SHA', type=str, help='dataset')
parser.add_argument('--data_path', default=r'/home/yangxiangpeng/.jupyter/data', type=str, help='path to dataset')
parser.add_argument('--lr', default=1e-4, type=float, help='initial learning rate')
parser.add_argument('--load', default=False, action='store_true', help='load checkpoint')
parser.add_argument('--save_path', default=r'/home/yangxiangpeng/.jupyter/SFANet-crowd-counting/logs/sha', type=str, help='path to save checkpoint')
parser.add_argument('--gpu', default=0, type=int, help='gpu id')
parser.add_argument('--log_path', default='./logs', type=str, help='path to log')

args = parser.parse_args()

print(args.data_path)

train_dataset = Dataset(args.data_path, args.dataset, True)
#print(train_dataset)
print(len(train_dataset))
train_loader = data.DataLoader(train_dataset, batch_size=args.bs, shuffle=True)
print(len(train_loader))
test_dataset = Dataset(args.data_path, args.dataset, False)
print(len(test_dataset))
test_loader = data.DataLoader(test_dataset, batch_size=1, shuffle=False)
print(len(test_loader))
          
         

#device = torch.device('cuda:' + str(args.gpu))
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
model = Model().to(device)
model.cuda()

writer = SummaryWriter(args.log_path)

mseloss = nn.MSELoss(reduction='sum').to(device)
bceloss = nn.BCELoss(reduction='sum').to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

if args.load:
    checkpoint = torch.load(os.path.join(args.save_path, 'checkpoint_latest.pth'))
    model.load_state_dict(checkpoint['model'])
    optimizer.load_state_dict(checkpoint['optimizer'])

    best_mae = torch.load(os.path.join(args.save_path, 'checkpoint_best.pth'))['mae']
    start_epoch = checkpoint['epoch'] + 1
else:
    best_mae = 999999
    start_epoch = 0

for epoch in range(start_epoch, start_epoch + args.epoch):
    loss_avg, loss_att_avg = 0.0, 0.0
    for i, (images, density, att) in enumerate(train_loader):
        images = images.to(device)
        density = density.to(device)
        att = att.to(device)
        outputs, attention = model(images)

        print('output:{:.2f} label:{:.2f}'.format(outputs.sum().item() / args.bs, density.sum().item() / args.bs))

        loss = mseloss(outputs, density) / args.bs
        loss_att = bceloss(attention, att) / args.bs * 0.1
        
        
        ssim_loss = pytorch_ssim.SSIM(window_size=11)

        #loss_sum = loss + loss_att
        loss_sum = loss + loss_att + (1 - ssim_loss(outputs,density))

        optimizer.zero_grad()
        loss_sum.backward()
        optimizer.step()

        loss_avg += loss.item()
        loss_att_avg += loss_att.item()

        print("Epoch:{}, Step:{}, Loss:{:.4f} {:.4f}".format(epoch, i, loss_avg / (i + 1), loss_att_avg / (i + 1)))
    
    writer.add_scalar('loss/train_loss', loss_avg / len(train_loader), epoch)
    writer.add_scalar('loss/train_loss_att', loss_att_avg / len(train_loader), epoch)

    model.eval()
    with torch.no_grad():
        mae, mse = 0.0, 0.0
        for i, (images, gt) in enumerate(test_loader):
            images = images.to(device)
            gt = gt.to(device)
            predict, _ = model(images)
            #print(gt.size())
            #print(predict.sum())
            #print(gt)
            print('predict:{:.2f} label:{:.2f}'.format(predict.sum().item(), gt.sum().item()))
            mae += torch.abs(predict.sum() - gt.sum()).item()
            mse += ((predict.sum() - gt.sum()) ** 2).item()

        mae /= len(test_loader)
        mse /= len(test_loader)
        mse = mse ** 0.5
        print('Epoch:', epoch, 'MAE:', mae, 'MSE:', mse)
        writer.add_scalar('eval/MAE', mae, epoch)
        writer.add_scalar('eval/MSE', mse, epoch)

        state = {'epoch': epoch, 'model': model.state_dict(), 'optimizer': optimizer.state_dict(), 'mae': mae,
                 'mse': mse}
        torch.save(state, os.path.join(args.save_path, 'checkpoint_latest.pth'))

        if mae < best_mae:
            best_mae = mae
            torch.save(state, os.path.join(args.save_path, 'checkpoint_best.pth'))
    model.train()
    

writer.close()

**Comment by Pongpisit-Thanasutives** [comment]
Thank you. I have seen your codes and spotted some inconsistencies in your implementation:

(1) I did not use the SSM loss.
(2) I did not use Adam. In the SHA experiment, I used LookaheadAdam(model.parameters(), lr=5e-4).
(3) Please train up to 1000 epochs, not 500, because the M-SFANet model is more complex in terms of #params.
(4) **The reproduced weights of M_SFANet with MAE=59.69 and MSE=95.64 are provided via the google drive link.** So you can check the saved epoch and the optimizer's state_dict.

P.S. I cannot check your preprocessing code, which is also important.

**Comment by knightyxp** [comment]
can not load your pretrain_pth
error like this:
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    model.load_state_dict(torch.load(model_path), device)
  File "/opt/conda/envs/torch17/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
        Missing key(s) in state_dict: "vgg.conv1_1.conv.weight", "vgg.conv1_1.conv.bias", "vgg.conv1_1.bn.weight", "vgg.conv1_1.bn.bias", "vgg.conv1_1.bn.running_mean", "vgg.conv1_1.bn.running_var", "vgg.conv1_2.conv.weight", "vgg.conv1_2.conv.bias", "vgg.conv1_2.bn.weight", "vgg.conv1_2.bn.bias", "vgg.conv1_2.bn.running_mean", "vgg.conv1_2.bn.running_var", "vgg.conv2_1.conv.weight", "vgg.conv2_1.conv.bias", "vgg.conv2_1.bn.weight", "vgg.conv2_1.bn.bias", "vgg.conv2_1.bn.running_mean", "vgg.conv2_1.bn.running_var", "vgg.conv2_2.conv.weight", "vgg.conv2_2.conv.bias", "vgg.conv2_2.bn.weight", "vgg.conv2_2.bn.bias", "vgg.conv2_2.bn.running_mean", "vgg.conv2_2.bn.running_var", "vgg.conv3_1.conv.weight", "vgg.conv3_1.conv.bias", "vgg.conv3_1.bn.weight", "vgg.conv3_1.bn.bias", "vgg.conv3_1.bn.running_mean", "vgg.conv3_1.bn.running_var", "vgg.conv3_2.conv.weight", "vgg.conv3_2.conv.bias", "vgg.conv3_2.bn.weight", "vgg.conv3_2.bn.bias", "vgg.conv3_2.bn.running_mean", "vgg.conv3_2.bn.running_var", "vgg.conv3_3.conv.weight", "vgg.conv3_3.conv.bias", "vgg.conv3_3.bn.weight", "vgg.conv3_3.bn.bias", "vgg.conv3_3.bn.running_mean", "vgg.conv3_3.bn.running_var", "vgg.conv4_1.conv.weight", "vgg.conv4_1.conv.bias", "vgg.conv4_1.bn.weight", "vgg.conv4_1.bn.bias", "vgg.conv4_1.bn.running_mean", "vgg.conv4_1.bn.running_var", "vgg.conv4_2.conv.weight", "vgg.conv4_2.conv.bias", "vgg.conv4_2.bn.weight", "vgg.conv4_2.bn.bias", "vgg.conv4_2.bn.running_mean", "vgg.conv4_2.bn.running_var", "vgg.conv4_3.conv.weight", "vgg.conv4_3.conv.bias", "vgg.conv4_3.bn.weight", "vgg.conv4_3.bn.bias", "vgg.conv4_3.bn.running_mean", "vgg.conv4_3.bn.running_var", "vgg.conv5_1.conv.weight", "vgg.conv5_1.conv.bias", "vgg.conv5_1.bn.weight", "vgg.conv5_1.bn.bias", "vgg.conv5_1.bn.running_mean", "vgg.conv5_1.bn.running_var", "vgg.conv5_2.conv.weight", "vgg.conv5_2.conv.bias", "vgg.conv5_2.bn.weight", "vgg.conv5_2.bn.bias", "vgg.conv5_2.bn.running_mean", "vgg.conv5_2.bn.running_var", "vgg.conv5_3.conv.weight", "vgg.conv5_3.conv.bias", "vgg.conv5_3.bn.weight", "vgg.conv5_3.bn.bias", "vgg.conv5_3.bn.running_mean", "vgg.conv5_3.bn.running_var", "spm.assp.aspp1.atrous_conv.weight", "spm.assp.aspp1.bn.weight", "spm.assp.aspp1.bn.bias", "spm.assp.aspp1.bn.running_mean", "spm.assp.aspp1.bn.running_var", "spm.assp.aspp2.atrous_conv.weight", "spm.assp.aspp2.bn.weight", "spm.assp.aspp2.bn.bias", "spm.assp.aspp2.bn.running_mean", "spm.assp.aspp2.bn.running_var", "spm.assp.aspp3.atrous_conv.weight", "spm.assp.aspp3.bn.weight", "spm.assp.aspp3.bn.bias", "spm.assp.aspp3.bn.running_mean", "spm.assp.aspp3.bn.running_var", "spm.assp.aspp4.atrous_conv.weight", "spm.assp.aspp4.bn.weight", "spm.assp.aspp4.bn.bias", "spm.assp.aspp4.bn.running_mean", "spm.assp.aspp4.bn.running_var", "spm.assp.global_avg_pool.1.weight", "spm.assp.global_avg_pool.2.weight", "spm.assp.global_avg_pool.2.bias", "spm.assp.global_avg_pool.2.running_mean", "spm.assp.global_avg_pool.2.running_var", "spm.assp.conv1.weight", "spm.assp.bn1.weight", "spm.assp.bn1.bias", "spm.assp.bn1.running_mean", "spm.assp.bn1.running_var", "spm.can.scales.0.1.weight", "spm.can.scales.1.1.weight", "spm.can.scales.2.1.weight", "spm.can.scales.3.1.weight", "spm.can.bottleneck.weight", "spm.can.bottleneck.bias", "spm.can.weight_net.weight", "spm.can.weight_net.bias", "amp.conv1.conv.weight", "amp.conv1.conv.bias", "amp.conv1.bn.weight", "amp.conv1.bn.bias", "amp.conv1.bn.running_mean", "amp.conv1.bn.running_var", "amp.conv2.conv.weight", "amp.conv2.conv.bias", "amp.conv2.bn.weight", "amp.conv2.bn.bias", "amp.conv2.bn.running_mean", "amp.conv2.bn.running_var", "amp.conv3.conv.weight", "amp.conv3.conv.bias", "amp.conv3.bn.weight", "amp.conv3.bn.bias", "amp.conv3.bn.running_mean", "amp.conv3.bn.running_var", "amp.conv4.conv.weight", "amp.conv4.conv.bias", "amp.conv4.bn.weight", "amp.conv4.bn.bias", "amp.conv4.bn.running_mean", "amp.conv4.bn.running_var", "amp.conv5.conv.weight", "amp.conv5.conv.bias", "amp.conv5.bn.weight", "amp.conv5.bn.bias", "amp.conv5.bn.running_mean", "amp.conv5.bn.running_var", "amp.conv6.conv.weight", "amp.conv6.conv.bias", "amp.conv6.bn.weight", "amp.conv6.bn.bias", "amp.conv6.bn.running_mean", "amp.conv6.bn.running_var", "amp.conv7.conv.weight", "amp.conv7.conv.bias", "amp.conv7.bn.weight", "amp.conv7.bn.bias", "amp.conv7.bn.running_mean", "amp.conv7.bn.running_var", "dmp.conv1.conv.weight", "dmp.conv1.conv.bias", "dmp.conv1.bn.weight", "dmp.conv1.bn.bias", "dmp.conv1.bn.running_mean", "dmp.conv1.bn.running_var", "dmp.conv2.conv.weight", "dmp.conv2.conv.bias", "dmp.conv2.bn.weight", "dmp.conv2.bn.bias", "dmp.conv2.bn.running_mean", "dmp.conv2.bn.running_var", "dmp.conv3.conv.weight", "dmp.conv3.conv.bias", "dmp.conv3.bn.weight", "dmp.conv3.bn.bias", "dmp.conv3.bn.running_mean", "dmp.conv3.bn.running_var", "dmp.conv4.conv.weight", "dmp.conv4.conv.bias", "dmp.conv4.bn.weight", "dmp.conv4.bn.bias", "dmp.conv4.bn.running_mean", "dmp.conv4.bn.running_var", "dmp.conv5.conv.weight", "dmp.conv5.conv.bias", "dmp.conv5.bn.weight", "dmp.conv5.bn.bias", "dmp.conv5.bn.running_mean", "dmp.conv5.bn.running_var", "dmp.conv6.conv.weight", "dmp.conv6.conv.bias", "dmp.conv6.bn.weight", "dmp.conv6.bn.bias", "dmp.conv6.bn.running_mean", "dmp.conv6.bn.running_var", "dmp.conv7.conv.weight", "dmp.conv7.conv.bias", "dmp.conv7.bn.weight", "dmp.conv7.bn.bias", "dmp.conv7.bn.running_mean", "dmp.conv7.bn.running_var", "conv_att.conv.weight", "conv_att.conv.bias", "conv_att.bn.weight", "conv_att.bn.bias", "conv_att.bn.running_mean", "conv_att.bn.running_var", "conv_out.conv.weight", "conv_out.conv.bias", "conv_out.bn.weight", "conv_out.bn.bias", "conv_out.bn.running_mean", "conv_out.bn.running_var". 
        Unexpected key(s) in state_dict: "epoch", "model", "optimizer", "mae", "mse".

**Comment by Pongpisit-Thanasutives** [comment]
The weights are stored in the "model" key. Like this one.
<img width="1172" alt="Screen Shot 2564-05-25 at 20 40 33" src="https://user-images.githubusercontent.com/33287321/119492055-9b6a1a00-bd99-11eb-80cf-09e3b2be9dc8.png">
